USE mydb;

-- Exercicio 2.1
-- Listar número, série e data de emissão das notas fiscais emitidas no mês de março de 2021, cujo nome da marca seja "BenoA"
SELECT
	NF.NR_NOTA_FISCAL,
    NF.NR_SERIE_NOTA_FISCAL,
    NF.DT_EMISSAO,
    MP.NM_MARCA_PRODUTO
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF
  ON NF.ID_NOTA_FISCAL = INF.ID_NOTA_FISCAL
INNER JOIN PRODUTOS AS P
  ON INF.SQ_ITEM_NOTA_FISCAL = P.CD_PRODUTO
INNER JOIN MARCAS_PRODUTOS AS MP
  ON P.ID_MARCA_PRODUTO = MP.ID_MARCA_PRODUTO
WHERE (NF.DT_EMISSAO BETWEEN '2021-03-01' AND '2021-03-31')
  AND BINARY MP.NM_MARCA_PRODUTO = 'BenoA';
  
-- Exercicio 2.2
-- Listar o nome dos grupos de produto que tiveram notas emitidas no período entre 01/02/2021 e 14/02/2021;
SELECT
  GP.NM_GRUPO_PRODUTO
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF
  ON NF.ID_NOTA_FISCAL = INF.ID_NOTA_FISCAL
INNER JOIN PRODUTOS AS P
  ON INF.SQ_ITEM_NOTA_FISCAL = P.CD_PRODUTO
INNER JOIN GRUPOS_PRODUTOS AS GP
  ON P.CD_GRUPO_PRODUTO = GP.CD_GRUPO_PRODUTO
WHERE (NF.DT_EMISSAO BETWEEN '2021-02-01' AND '2021-02-14')
GROUP BY GP.NM_GRUPO_PRODUTO;
