SELECT * FROM mydb.EMPRESAS;


-- Exercicio 2.1
SELECT
	NF.NR_NOTA_FISCAL,
    NF.NR_SERIE_NOTA_FISCAL,
    NF.DT_EMISSAO
FROM mydb.NOTAS_FISCAIS AS NF
INNER JOIN mydb.ITENS_NOTAS_FISCAIS AS INF
  ON NF.ID_NOTA_FISCAL = INF.ID_NOTA_FISCAL
INNER JOIN mydb.PRODUTOS AS P
  ON INF.SQ_ITEM_NOTA_FISCAL = P.CD_PRODUTO
INNER JOIN mydb.MARCAS_PRODUTOS AS MP
  ON P.ID_MARCA_PRODUTO = MP.ID_MARCA_PRODUTO
WHERE (NF.DT_EMISSAO BETWEEN '2021-03-01' AND '2021-03-31')
  AND MP.NM_MARCA_PRODUTO = "BenoA";